### ISSUE TITLE
Question:  how does this related to MongoDB

### ISSUE THREAD

**Issue by zhihuiFan** [fiddus/datatables-query#5]
Actually I used MongoDB very much during my project. every time,  I write 
python code to read mongo,  URL to bind to that function and then on the UI, I use Datatable with ajax call to get the data. 

I know mongo has some restful API supported by default.  My question is will  `databases-query`  use the MongoDB restful API directly.  If so  I will not need to read from mongo,  write URL anymore?

if so, how the username/password information is maintained.  

Thanks for your time

**Comment by vinicius0026** [comment]
I'm sorry, but I didn't understand your issue. `datatables-query` is used to transform data extracted from MongoDB (via JavaScript ODM lib [Mongoose](https://github.com/Automattic/mongoose)) into the format expected by [Datatables](https://datatables.net/). 
`datatables-query` should only be used to this purpose, and doesn't replace, in any way, other operations in the database, that could use Mongoose or MongoDB calls to perform queries to store or retrieve data.

**Comment by zhihuiFan** [comment]
sorry for my unclear question statement:(  My questions before is how the datatable-query get the data.  
Looks like mongoose is a service side lib,  and we need to use it on the server side, it returns the datatable wanted format. then everything works. 

Thanks for your reply!
