### ISSUE TITLE
QUERY: How to populate other document?

### ISSUE THREAD

**Issue by karthik14k** [fiddus/datatables-query#7]
Hi, 
I am able to use this package and get the data on front-end side. But does it support to populate other document and display that data on front-end side?

**Comment by vinicius0026** [comment]
Hey @karthik14k 
I'm not sure I understood your question. If you are getting the data on the front end, as you said you are, then you can manipulate and display it as you like. Although this module was intended primarily to be used in conjunction with datatables jquery module to display tabular data.

**Comment by karthik14k** [comment]
Hey @vinicius0026 thanks for the response.
I figured it out, as you said, I manipulated the data and displayed it.
Thank you :)
